/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData vector = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector__2_ = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector__1_ = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polygonal_close = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icon_1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData referesh2 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed2 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date_time = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date2 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cell_prices_in_days = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_drawer = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grills = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kitchen = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fluent_emoji_high_contrast_toilet = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData living_rooms____seatings = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat3 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info3 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData between_numbers2 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uil_calender = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icon__5_ = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fluent_save_16_filled = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask_group = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invite_friend = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theme = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_web_sync = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_checked = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subtract = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polygonal_chat = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polygonal_date_time = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polygonal_date = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polygonal_close_1 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polygonl_more = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_place = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_vector = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_message = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_selected = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_morning_and_evening_reserved = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_evening_reserved = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_morning_reserved = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_not_reserved = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_arrow_left = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_arrow_right = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_profile_outlined = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date1 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outlined = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fill_heart = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_heart_outlined = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_share = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ri_moon_line = IconData(0xeba6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_squared = IconData(0xf14a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
